import {scheduleCaption} from '@/lib/core';
import {body,db,env,errorResponse,freshRoom,json,rate,requireOperator,requireSession,room,settings,terminate,viewerToken} from '@/lib/server';
import {AppError,hangup,openCall,providerConfig,rates,translate} from '@/lib/providers';
import {publicSettings,sanitizeSettings} from '@/lib/settings';
export async function GET(req:Request){try{await requireOperator(req);const r=await freshRoom();const c=providerConfig(env,settings(r));return json({active:!!r.session,started:r.started,ended:r.ended,hidden:!!r.hidden,settings:settings(r),caption:r.expires>Date.now()?r.caption:'',source:r.source,revision:r.revision,published:r.published,expires:r.expires,serverNow:Date.now(),translationCost:r.translation_cost,unknownCost:!!r.unknown_cost,inputTokens:r.input_tokens,outputTokens:r.output_tokens,provider:c.provider,model:c.model,asrModel:env.ASR_MODEL||'gpt-live-transcribe',ready:!!env.OPENAI_API_KEY&&!!c.key,prices:rates(env,settings(r)),viewerToken:await viewerToken(r)});}catch(e){return errorResponse(e);}}
export async function POST(req:Request){try{await requireOperator(req);const b=await body(req);await rate('control',300);const r=await freshRoom();
 if(b.action==='settings'){if(r.session)throw new AppError('Меняйте настройки между сеансами.',409);const s=sanitizeSettings(b.settings||{});await db().prepare('UPDATE room SET settings=?, revision=revision+1 WHERE id=1').bind(JSON.stringify(s)).run();return json({settings:s});}
 if(b.action==='screen'){if(b.rotate){await db().prepare('UPDATE room SET viewer_epoch=viewer_epoch+1 WHERE id=1').run();return json({viewerToken:await viewerToken(await room())});}await db().prepare("UPDATE room SET hidden=?,caption=CASE WHEN ? THEN '' ELSE caption END,expires=CASE WHEN ? THEN 0 ELSE expires END,revision=revision+1 WHERE id=1").bind(typeof b.hidden==='boolean'?Number(b.hidden):r.hidden,!!b.clear,!!b.clear).run();return json({ok:true});}
 if(b.action==='start'){
  if(!env.OPENAI_API_KEY||!providerConfig(env).key)throw new AppError('Добавьте серверные API-ключи распознавания и перевода.',503);
  await rate('start',8);if(r.session)throw new AppError('Уже работает другой сеанс.',409);if(r.call_id){try{await hangup(env,r.call_id);}catch(e){console.error('Previous Realtime call could not be closed before restart',e);}}const id=crypto.randomUUID(),now=Date.now();const updated=await db().prepare("UPDATE room SET session=?,lease=?,started=?,ended=0,seq=0,job=NULL,job_until=0,caption='',source='',context='[]',expires=0,hidden=0,translation_cost=0,unknown_cost=0,input_tokens=0,output_tokens=0,last_request=0,call_id=NULL,connect_lock=NULL,revision=revision+1 WHERE id=1 AND session IS NULL AND job_until<? RETURNING id").bind(id,now+25000,now,now).first();if(!updated)throw new AppError('Уже работает другой сеанс. Остановите его в пульте.',409);return json({session:id,started:now});
 }
 if(b.action==='stop'){if(b.session)requireSession(r,b.session);await terminate(r);return json({ok:true});}
 if(b.action==='evaluate'){
  if(r.session)throw new AppError('Проверка текста доступна между сеансами.',409);await rate('evaluate',5);const text=String(b.text||'').trim();if(!text||text.length>1800)throw new AppError('Введите русский текст до 1800 символов.');const token=crypto.randomUUID();const locked=await db().prepare('UPDATE room SET job=?,job_until=? WHERE id=1 AND job_until<? RETURNING id').bind(token,Date.now()+20000,Date.now()).first();if(!locked)throw new AppError('Предыдущая проверка ещё выполняется.',409);try{const began=Date.now();const result=await translate(env,text,[],settings(r));return json({...result,translationMs:Date.now()-began,provider:providerConfig(env,settings(r)).provider,model:providerConfig(env,settings(r)).model});}finally{await db().prepare('UPDATE room SET job=NULL,job_until=0 WHERE id=1 AND job=?').bind(token).run();}
 }
 requireSession(r,b.session);
 if(b.action==='heartbeat'){const prices=rates(env,settings(r));const estimated=(Date.now()-r.started)/60000*(prices.asr??0)+r.translation_cost;if(estimated>=settings(r).budget){await terminate(r);throw new AppError('Достигнут заданный ориентир бюджета. Сеанс остановлен.',402);}await db().prepare('UPDATE room SET lease=? WHERE id=1 AND session=?').bind(Date.now()+25000,b.session).run();return json({ok:true,estimatedCost:estimated,unknownCost:!!r.unknown_cost||prices.asr===null});}
 if(b.action==='connect'){
  await rate('connect',8);if(typeof b.sdp!=='string'||b.sdp.length>20000)throw new AppError('Некорректное подключение микрофона.');const lock=crypto.randomUUID();const locked=await db().prepare('UPDATE room SET connect_lock=? WHERE id=1 AND session=? AND connect_lock IS NULL RETURNING id').bind(lock,b.session).first();if(!locked)throw new AppError('Подключение уже создаётся.',409);
  let opened:{sdp:string;id:string}|undefined;try{if(r.call_id)await hangup(env,r.call_id);opened=await openCall(env,b.sdp,settings(r));const saved=await db().prepare('UPDATE room SET call_id=?,connect_lock=NULL,lease=? WHERE id=1 AND session=? AND connect_lock=? RETURNING id').bind(opened.id,Date.now()+25000,b.session,lock).first();if(!saved){await hangup(env,opened.id);throw new AppError('Запуск отменён.',409);}return json({sdp:opened.sdp});}catch(e){if(opened)await hangup(env,opened.id).catch(()=>{});await db().prepare('UPDATE room SET connect_lock=NULL WHERE id=1 AND connect_lock=?').bind(lock).run();throw e;}
 }
 if(b.action==='translate'){
  const seq=b.seq;const source=String(b.source||'').trim();if(!Number.isSafeInteger(seq)||seq<1||!source||source.length>2200)throw new AppError('Фраза слишком длинная или имеет неверный номер.');
  if(seq===r.seq)return json({duplicate:true,text:r.caption});if(seq<r.seq)throw new AppError('Устаревшая фраза отклонена.',409);if(seq!==r.seq+1)throw new AppError('Нарушен порядок фраз. Сеанс остановлен, чтобы не пропустить речь.',409);
  const now=Date.now();const job=crypto.randomUUID();const locked=await db().prepare('UPDATE room SET job=?,job_until=?,last_request=? WHERE id=1 AND session=? AND seq=? AND job_until<? AND last_request<? RETURNING id').bind(job,now+18000,now,b.session,seq-1,now,now-200).first();if(!locked)throw new AppError('Перевод уже обрабатывается. Дождитесь результата.',409);
  try{const began=Date.now();let result;try{result=await translate(env,source,JSON.parse(r.context),settings(r));}catch(e){await db().prepare('UPDATE room SET unknown_cost=1 WHERE id=1 AND session=?').bind(b.session).run();throw e;}const context=[...JSON.parse(r.context),{ru:source,en:result.text}].slice(-4);const finished=Date.now();const display=scheduleCaption(result.text,settings(r));const saved=await db().prepare('UPDATE room SET seq=?,caption=?,source=?,context=?,published=?,expires=?,revision=revision+1,translation_cost=translation_cost+?,unknown_cost=MAX(unknown_cost,?),input_tokens=input_tokens+?,output_tokens=output_tokens+?,job=NULL,job_until=0 WHERE id=1 AND session=? AND seq=? AND job=? AND lease>? RETURNING revision').bind(seq,result.text,source,JSON.stringify(context),finished,finished+Math.max(settings(r).clearSeconds*1000,display.holdMs),result.cost??0,result.cost===null?1:0,result.input,result.output,b.session,seq-1,job,finished).first<{revision:number}>();if(!saved)throw new AppError('Сеанс уже остановлен. Поздний перевод не показан.',409);return json({...result,revision:saved.revision,published:finished,expires:finished+Math.max(settings(r).clearSeconds*1000,display.holdMs),serverNow:Date.now(),displayMs:display.holdMs,translationMs:finished-began,settings:publicSettings(settings(r))});
  }finally{await db().prepare('UPDATE room SET job=NULL,job_until=0 WHERE id=1 AND job=?').bind(job).run();}
 }
 throw new AppError('Неизвестная команда.');
}catch(e){return errorResponse(e);}}
