'use client';
import {useEffect,useMemo,useState} from 'react';
import {captionPages} from '@/lib/core';
import {defaults,type Settings} from '@/lib/settings';
type Style=Pick<Settings,'fontSize'|'color'|'background'|'transparent'|'position'|'margin'|'lines'|'clearSeconds'>;
type OutputData={settings:Style;revision:number;text:string;ttl:number};
function CaptionPages({text,settings=defaults}:{text:string;settings?:Style}){const [page,setPage]=useState(0);const columns=Math.max(16,Math.floor(1920*(1-settings.margin*.02)/(settings.fontSize*.69)));const pages=useMemo(()=>captionPages(text,columns,settings.lines),[text,columns,settings.lines]);useEffect(()=>{if(pages.length<2)return;let n=0;const timer=setInterval(()=>{n++;setPage(Math.min(n,pages.length-1));},3000);return()=>clearInterval(timer);},[pages]);const placement=settings.position==='bottom'?{bottom:`${settings.margin}%`}:settings.position==='top'?{top:`${settings.margin}%`}:{top:'50%',transform:'translateY(-50%)'};return <div className="caption-frame" style={{...placement,padding:`0 ${settings.margin}%`}}><p className="caption" lang="en" style={{color:settings.color,fontSize:`${settings.fontSize/19.2}cqw`}}>{pages[page]||''}</p></div>;}
export function Captions({text,settings=defaults}:{text:string;settings?:Style}) {
 return <CaptionPages key={JSON.stringify([text,settings.fontSize,settings.margin,settings.lines])} text={text} settings={settings}/>;
}
export default function Output(){const [text,setText]=useState('');const [version,setVersion]=useState(-1);const [s,setS]=useState<Style>(defaults);const [black,setBlack]=useState(false);useEffect(()=>{setBlack(new URLSearchParams(window.location.search).get('background')==='black');},[]);useEffect(()=>{let closed=false;let clear:ReturnType<typeof setTimeout>;let timer:ReturnType<typeof setTimeout>;let revision=-1;const abort=new AbortController();const poll=async()=>{try{const r=await fetch('/api/output',{cache:'no-store',signal:abort.signal});if(!r.ok)throw new Error();const data=await r.json() as OutputData;if(closed)return;setS(data.settings);if(data.revision!==revision){revision=data.revision;setVersion(data.revision);setText(data.text);}if(!data.text)setText('');clearTimeout(clear);clear=setTimeout(()=>setText(''),Math.min(data.ttl,15000));timer=setTimeout(poll,350);}catch{if(!closed){setText('');revision=-1;timer=setTimeout(poll,1500);}}};const start=async()=>{const token=location.hash.slice(1);if(token){const r=await fetch('/api/output',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token}),signal:abort.signal});history.replaceState(null,'',location.pathname+location.search);if(!r.ok)return;}await poll();};void start().catch(()=>{});return()=>{closed=true;abort.abort();clearTimeout(clear);clearTimeout(timer);};},[]);return <div className="output-stage" style={{background:black?s.background:s.transparent?'transparent':s.background}}><style>{'html, body {background:transparent!important;}'}</style><Captions key={version} text={text} settings={s}/></div>;}
