import {AudioChunks} from './audio-chunks';
import {TranscriptOrder,splitPhrases,type SpeechItem} from './core';
import type {Settings} from './settings';
type ApiResult=Record<string,unknown>;
export async function api<T extends ApiResult=ApiResult>(action:string,data:Record<string,unknown>={},signal?:AbortSignal){const r=await fetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...data}),signal:signal?AbortSignal.any([signal,AbortSignal.timeout(22000)]):AbortSignal.timeout(22000)});const result=await r.json() as ApiResult;if(!r.ok)throw new Error(typeof result.error==='string'?result.error:'Не удалось связаться с сервером.');return result as T;}
export type LiveUpdate={status?:string;partial?:string;source?:string;text?:string;level?:number;pending?:number;translationMs?:number;estimatedMs?:number;error?:string;gap?:boolean;cost?:number;running?:boolean;started?:number};
export class LiveSession {
 session='';private pc:RTCPeerConnection|null=null;private dc:RTCDataChannel|null=null;private stream:MediaStream|null=null;private audio:AudioContext|null=null;private cancelled=false;private abort=new AbortController();private timers:ReturnType<typeof setInterval>[]=[];private frame=0;private order=new TranscriptOrder();private chunks=new AudioChunks();private queue:SpeechItem[]=[];private busy=false;private seq=0;private generation=0;private reconnecting=false;private openedAt=0;private lastSpeech=0;private reconnects=0;private ready=false;private startedAt=0;private lastGoodHeartbeat=0;private wake:WakeLockSentinel|null=null;
 constructor(private update:(v:LiveUpdate)=>void){}
 async start(device:string,s:Settings){if(this.cancelled)return;try{
  if(!navigator.mediaDevices?.getUserMedia)throw new Error('Откройте приложение по HTTPS или на localhost.');
  this.update({status:'Разрешение на микрофон…'});
  const audio={echoCancellation:!s.cleanInput,noiseSuppression:!s.cleanInput,autoGainControl:!s.cleanInput};
  try {
   this.stream=await navigator.mediaDevices.getUserMedia({audio:{...(device&&device!=='system'?{deviceId:{exact:device}}:{}),...audio},video:false});
  } catch(e) {
   // Device ids can become stale when a USB/Bluetooth microphone is removed.
   if(device && e instanceof DOMException && (e.name==='OverconstrainedError'||e.name==='NotFoundError')) {
    this.update({status:'Выбранный микрофон недоступен, использую системный…'});
    this.stream=await navigator.mediaDevices.getUserMedia({audio,video:false});
   } else throw e;
  }
  if(this.cancelled){this.stream.getTracks().forEach(t=>t.stop());return;}
  const track=this.stream.getAudioTracks()[0];
  if(!track)throw new Error('Браузер не вернул аудиодорожку. Проверьте выбранный микрофон.');
  track.onended=()=>void this.fail('Микрофон отключён. Подключите его и начните новый сеанс.');
  this.audio=new AudioContext();await this.audio.resume();if(this.cancelled)return;const analyser=this.audio.createAnalyser();analyser.fftSize=512;this.audio.createMediaStreamSource(this.stream).connect(analyser);const samples=new Float32Array(analyser.fftSize);const meter=()=>{if(this.cancelled)return;analyser.getFloatTimeDomainData(samples);let sum=0;for(const x of samples)sum+=x*x;this.update({level:Math.min(1,Math.sqrt(sum/samples.length)*4)});this.frame=requestAnimationFrame(meter);};meter();
  const started=await api<{session:string;started:number}>('start',{},this.abort.signal);this.session=started.session;this.startedAt=started.started;this.lastGoodHeartbeat=Date.now();if(this.cancelled){await api('stop',{session:this.session});return;}
  this.update({running:true,started:this.startedAt});this.timers.push(setInterval(()=>this.flushAudio(),100));this.timers.push(setInterval(()=>void this.heartbeat(),5000));this.timers.push(setInterval(()=>{if(Date.now()-this.lastGoodHeartbeat>18000)void this.fail('Сервер недоступен. Захват остановлен; проверьте интернет.');if(this.order.oldest&&performance.now()-this.order.oldest>25000)void this.fail('Распознавание задержалось более чем на 25 секунд. Неподтверждённая речь не переведена.');if(this.queue[0]&&performance.now()-this.queue[0].receivedAt>18000)void this.fail('Перевод отстаёт более чем на 18 секунд. Сеанс остановлен; ожидающие фразы не показаны.');if(this.ready&&Date.now()-this.openedAt>50*60*1000&&!this.busy&&this.queue.length===0&&Date.now()-this.lastSpeech>1500)void this.reconnect(s,'Плановое обновление AI-соединения. На границе возможен пропуск речи.');},1000));
  window.addEventListener('pagehide',this.onPageHide);window.addEventListener('offline',this.onOffline);try{this.wake=await navigator.wakeLock?.request('screen');}catch{}
  await this.connect(s);
 }catch(e){await this.fail(micError(e));}}
 private onPageHide=()=>{this.dispose();if(this.session)void fetch('/api/control',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'stop',session:this.session}),keepalive:true}).catch(()=>{});};
 private onOffline=()=>{void this.fail('Интернет отключён. Сеанс остановлен; речь во время сбоя не записывается.');};
 private async heartbeat(){if(this.cancelled||!this.session)return;try{const h=await api<{estimatedCost?:number}>('heartbeat',{session:this.session},this.abort.signal);this.lastGoodHeartbeat=Date.now();this.update({cost:h.estimatedCost});}catch(e){if(!this.cancelled)await this.fail(e instanceof Error?e.message:'Нет связи с сервером.');}}
 private async connect(s:Settings){
  this.ready=false;this.update({status:'Подключение к распознаванию…'});const generation=++this.generation;const pc=new RTCPeerConnection();this.pc=pc;this.stream!.getAudioTracks().forEach(t=>pc.addTrack(t,this.stream!));const dc=pc.createDataChannel('oai-events');this.dc=dc;this.order.reset();this.chunks.reset();
  dc.onmessage=e=>{if(generation!==this.generation||this.cancelled)return;try{const event=JSON.parse(e.data);if(this.chunks.handle(event,performance.now()))return;if(event.type==='error'||event.type==='conversation.item.input_audio_transcription.failed'){void this.fail('AI не смог распознать речь. Сеанс остановлен; проверьте ключ, язык и уровень звука.');return;}if(event.type==='input_audio_buffer.speech_started'||event.type==='input_audio_buffer.committed')this.lastSpeech=Date.now();const result=this.order.handle(event,performance.now());if(result.partial!==undefined)this.update({partial:result.partial});for(const item of result.ready){for(const source of splitPhrases(item.source)){this.queue.push({...item,source});}this.update({partial:'',pending:this.queue.length});if(this.queue.length>10){void this.fail('Очередь превысила 10 фраз. Сеанс остановлен; часть речи осталась непереведённой.');return;}void this.pump();}}catch{void this.fail('Нарушен поток событий распознавания. Начните новый сеанс.');}};
  pc.onconnectionstatechange=()=>{if(generation!==this.generation||this.cancelled)return;if(pc.connectionState==='failed'||pc.connectionState==='disconnected')void this.reconnect(s,'Связь с AI прервалась. Речь на границе переподключения могла быть пропущена.');};
  const offer=await pc.createOffer();await pc.setLocalDescription(offer);const response=await api<{sdp:string}>('connect',{session:this.session,sdp:offer.sdp},this.abort.signal);if(this.cancelled||generation!==this.generation)return;await pc.setRemoteDescription({type:'answer',sdp:response.sdp});
  await new Promise<void>((resolve,reject)=>{if(dc.readyState==='open'){resolve();return;}const timer=setTimeout(()=>reject(new Error('AI не открыл поток событий.')),10000);dc.onopen=()=>{clearTimeout(timer);resolve();};this.abort.signal.addEventListener('abort',()=>{clearTimeout(timer);reject(new Error('Запуск отменён.'));},{once:true});});if(this.cancelled)return;this.ready=true;this.openedAt=Date.now();this.update({status:'Слушаю русский',running:true});
 }
 private flushAudio(){if(this.cancelled||!this.ready||this.dc?.readyState!=='open')return;try{this.chunks.tick(performance.now(),event=>this.dc!.send(JSON.stringify(event)));}catch(e){void this.fail(micError(e));}}
 private async reconnect(s:Settings,message:string){if(this.reconnecting||this.cancelled)return;this.reconnecting=true;this.ready=false;this.update({status:'Переподключение…',error:message,gap:true});if(++this.reconnects>6){await this.fail('Слишком много разрывов соединения. Проверьте интернет и начните новый сеанс.');return;}this.generation++;this.pc?.close();this.dc?.close();this.order.reset();try{await new Promise<void>(resolve=>{const t=setTimeout(resolve,Math.min(8000,500*2**(this.reconnects-1)));this.abort.signal.addEventListener('abort',()=>{clearTimeout(t);resolve();},{once:true});});if(!this.cancelled)await this.connect(s);}catch(e){await this.fail(micError(e));}finally{this.reconnecting=false;}}
 private async pump(){if(this.busy||this.cancelled)return;this.busy=true;try{while(this.queue.length&&!this.cancelled){const item=this.queue.shift()!;this.update({source:item.source,pending:this.queue.length+1});const r=await api<{text:string;translationMs?:number;displayMs?:number}>('translate',{session:this.session,seq:++this.seq,source:item.source},this.abort.signal);if(this.cancelled)return;await new Promise<void>(resolve=>requestAnimationFrame(()=>resolve()));this.update({text:r.text,translationMs:r.translationMs,estimatedMs:item.endedAt===null?undefined:performance.now()-item.endedAt,pending:this.queue.length});}}catch(e){if(!this.cancelled)await this.fail(micError(e));}finally{this.busy=false;}}
 private dispose(){this.cancelled=true;this.ready=false;this.generation++;this.abort.abort();this.timers.forEach(clearInterval);cancelAnimationFrame(this.frame);this.dc?.close();this.pc?.close();this.stream?.getTracks().forEach(t=>t.stop());const audio=this.audio;this.audio=null;if(audio&&audio.state!=='closed')void audio.close().catch(()=>{});const wake=this.wake;this.wake=null;if(wake)void wake.release().catch(()=>{});this.queue=[];this.order.reset();this.chunks.reset();window.removeEventListener('pagehide',this.onPageHide);window.removeEventListener('offline',this.onOffline);this.update({running:false,level:0,pending:0,partial:''});}
 async stop(){this.dispose();this.update({status:'Остановка…'});try{if(this.session)await api('stop',{session:this.session});this.update({status:'Сеанс завершён'});}catch(e){this.update({status:'Захват остановлен',error:micError(e)});}}
 private async fail(message:string){if(this.cancelled)return;await this.stop();this.update({error:message,status:'Требуется внимание'});}
}
export function micError(e:unknown){if(e instanceof DOMException){if(e.name==='NotAllowedError')return 'Доступ к микрофону запрещён. Разрешите его в браузере.';if(e.name==='NotFoundError'||e.name==='OverconstrainedError')return 'Выбранный микрофон не найден. Обновите список устройств.';if(e.name==='NotReadableError')return 'Микрофон занят другим приложением или отключён.';}return e instanceof Error?e.message:'Не удалось запустить перевод.';}
