import {env as bindings} from 'cloudflare:workers';
import {AppError,hangup,type Env} from './providers';
import {defaults,sanitizeSettings} from './settings';
export const env=bindings as unknown as Env;
export const db=()=> (bindings as unknown as {DB:D1Database}).DB;
export type Room={id:number;settings:string;viewer_epoch:number;session:string|null;lease:number;started:number;ended:number;call_id:string|null;connect_lock:string|null;seq:number;job:string|null;job_until:number;revision:number;caption:string;source:string;context:string;published:number;expires:number;hidden:number;translation_cost:number;unknown_cost:number;input_tokens:number;output_tokens:number;last_request:number};
export async function room(){await db().prepare('INSERT OR IGNORE INTO room (id,settings) VALUES (1,?)').bind(JSON.stringify(defaults)).run();return (await db().prepare('SELECT * FROM room WHERE id=1').first<Room>())!;}
export function settings(r:Room){return sanitizeSettings(JSON.parse(r.settings));}
const encoder=new TextEncoder();
export async function sign(value:string){const secret=env.LOCAL_NO_AUTH==='true'?'church-local-viewer-signing-key':env.OPERATOR_PASSWORD;if(!secret||secret.length<16)throw new AppError('Администратор должен задать OPERATOR_PASSWORD (не менее 16 символов) на сервере.',503);const key=await crypto.subtle.importKey('raw',encoder.encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);return Array.from(new Uint8Array(await crypto.subtle.sign('HMAC',key,encoder.encode(value)))).map(x=>x.toString(16).padStart(2,'0')).join('');}
export async function equal(a:string,b:string){return (await sign(a))===(await sign(b));}
export function cookie(req:Request,name:string){return req.headers.get('cookie')?.split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1)||'';}
export function cookieHeader(req:Request,name:string,value:string,age:number){return `${name}=${value}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${age}${new URL(req.url).protocol==='https:'?'; Secure':''}`;}
export function json(value:unknown,status=200,extra:Record<string,string>={}){return Response.json(value,{status,headers:{'Cache-Control':'no-store','Referrer-Policy':'no-referrer','X-Content-Type-Options':'nosniff',...extra}});}
export function localAccess(req:Request){return env.LOCAL_NO_AUTH==='true'&&['localhost','127.0.0.1','[::1]'].includes(new URL(req.url).hostname);}
export async function authenticated(req:Request){if(localAccess(req))return true;if(!env.OPERATOR_PASSWORD||env.OPERATOR_PASSWORD.length<16)return false;const [expires,signature]=cookie(req,'church_operator').split('.');if(!expires||!signature||Number(expires)<Date.now())return false;return equal(signature,await sign('operator:'+expires));}
export async function requireOperator(req:Request){if(!await authenticated(req))throw new AppError('Войдите в пульт оператора.',401);}
export function checkOrigin(req:Request){const o=req.headers.get('origin');if(o!==new URL(req.url).origin)throw new AppError('Запрос из другого приложения отклонён.',403);}
export async function body(req:Request){checkOrigin(req);if(!req.headers.get('content-type')?.startsWith('application/json'))throw new AppError('Ожидался JSON.',415);const reader=req.body?.getReader();if(!reader)throw new AppError('Пустой запрос.');let size=0;const chunks:Uint8Array[]=[];while(true){const {value,done}=await reader.read();if(done)break;size+=value.length;if(size>40000){await reader.cancel();throw new AppError('Слишком большой запрос.',413);}chunks.push(value);}const bytes=new Uint8Array(size);let offset=0;for(const c of chunks){bytes.set(c,offset);offset+=c.length;}try{return JSON.parse(new TextDecoder().decode(bytes));}catch{throw new AppError('Некорректный запрос.');}}
export async function rate(key:string,max:number,period=60000){const window=Math.floor(Date.now()/period);const row=await db().prepare('INSERT INTO rate_limits (key,window,count) VALUES (?,?,1) ON CONFLICT(key) DO UPDATE SET count=CASE WHEN window=excluded.window THEN count+1 ELSE 1 END, window=excluded.window RETURNING count').bind(key,window).first<{count:number}>();if((row?.count??0)>max)throw new AppError('Слишком много запросов. Подождите минуту.',429);}
export async function terminate(r:Room){if(!r.session)return;await db().prepare("UPDATE room SET session=NULL, lease=0, ended=?, caption='', source='', context='[]', expires=0, revision=revision+1, job=NULL, job_until=0, connect_lock=NULL WHERE id=1 AND session=?").bind(Date.now(),r.session).run();try{await hangup(env,r.call_id);}catch(e){console.error('Realtime hangup failed after session termination',e);}finally{await db().prepare('UPDATE room SET call_id=NULL WHERE id=1 AND call_id=?').bind(r.call_id).run();}}
export async function freshRoom(){let r=await room();if(r.session&&r.lease<Date.now()){await terminate(r);r=await room();}return r;}
export function requireSession(r:Room,id:unknown){if(typeof id!=='string'||!id||r.session!==id||r.lease<Date.now())throw new AppError('Сеанс завершён или запущен в другой вкладке.',409);}
export function errorResponse(e:unknown){if(!(e instanceof AppError))console.error('Unhandled API error',e);return json({error:e instanceof AppError?e.message:'Внутренняя ошибка. Обновите пульт; если ошибка повторится, проверьте сервер.'},e instanceof AppError?e.status:500);}
export async function viewerToken(r:Room){return `${r.viewer_epoch}.${await sign('viewer:'+r.viewer_epoch)}`;}
export async function validViewer(value:string,r:Room){return value.length<200&&await equal(value,await viewerToken(r));}
